local opt = vim.opt

opt.smartcase = true
opt.smartindent = true
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.cursorline = true
opt.showmode = false
opt.expandtab = true
opt.shiftwidth = 4
opt.tabstop = 4
opt.numberwidth = 4
opt.number = true
opt.wrap = false
opt.undofile = false
opt.writebackup = false
opt.scrolloff = 8
opt.sidescrolloff = 8
-- opt.cursorline = true
opt.signcolumn = "yes"
