local opt = vim.opt
opt.smartcase = true
opt.smartindent = true
opt.termguicolors = true
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.cursorline = true
opt.showmode = false
opt.expandtab = true
opt.shiftwidth = 4
opt.tabstop = 4
opt.numberwidth = 4
opt.relativenumber = true
opt.wrap = false
opt.undofile = false
opt.writebackup = false
opt.scrolloff = 10
opt.hidden = true
opt.sidescrolloff = 8
-- opt.cursorline = true
opt.laststatus=3
vim.cmd [[filetype plugin indent on]]
